# Generated by Django 5.2.5 on 2025-08-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsolationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_type', models.CharField(max_length=100)),
                ('cave_site', models.CharField(max_length=100)),
                ('sampling_point', models.IntegerField()),
                ('sampling_date', models.DateField()),
            ],
        ),
    ]
