# Generated by Django 5.2.5 on 2025-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isolation_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolationsource',
            name='sampling_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='isolationsource',
            name='sampling_point',
            field=models.IntegerField(null=True),
        ),
    ]
